---
- name: Configurar ACR y subir imágenes
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - acr

- name: Configurar VM Linux, instalar Podman y NGINX
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - vm

- name: Desplegar Redis en AKS
  hosts: all
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - aks
