apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: mi-container
        image: acrpractica2.azurecr.io/redis:latestasa
        imagePullSecrets:

